stages:
    - build
    - publish
    - deploy
    
before_script:
    - "ls"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

publish:
    stage: publish
    script:
        - "dotnet publish -c Release -o ./Publish"
    dependencies:
    - build
    
deploy:
    stage: deploy
    script:
        - "systemctl stop supervisord"
    dependencies:
    - publish


