stages:
    - build
    
before_script:
    - "ls"
    - "dotnet restore"

build:
    stage: build
    only:
        - schedules
    tags:
        - prod
    script:
        - "dotnet publish -c Release -o /opt/WorkFlowAPI/DotnetPublish/"
        - "supervisorctl stop all"
        - "rm -rf /opt/WorkFlowAPI/dotnetcore_modules_backup"
        - "mv /opt/WorkFlowAPI/dotnetcore_modules /opt/WorkFlowAPI/dotnetcore_modules_backup"
        - "mkdir /opt/WorkFlowAPI/dotnetcore_modules" 
        - "cp -a /opt/WorkFlowAPI/DotnetPublish/. /opt/WorkFlowAPI/dotnetcore_modules/"
        - "supervisorctl start all"

