stages:
    - build
    
before_script:
    - "ls"
    - "dotnet restore"

build:
    stage: build
    only:
        - schedules
    tags:
        - dashboard
    script:
        - "sudo dotnet publish -c Release -o /opt/WorkFlowAPI/DotnetPublish/"
        - "sudo systemctl stop supervisord"
        - "sudo rm -rf /opt/WorkFlowAPI/dotnetcore_modules_backup"
        - "sudo mv /opt/WorkFlowAPI/dotnetcore_modules /opt/WorkFlowAPI/dotnetcore_modules_backup"
        - "sudo mkdir /opt/WorkFlowAPI/dotnetcore_modules" 
        - "sudo cp -a /opt/WorkFlowAPI/DotnetPublish/. /opt/WorkFlowAPI/dotnetcore_modules/"
        - "sudo systemctl start supervisord"
        - "sudo rm -rf /opt/WorkFlowAPI/DotnetPublish"

