stages:
    - build
    
before_script:
    - "ls"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet publish -c Release -o ./Publish"
        - "systemctl stop supervisord"
        - "mv /opt/WorkFlowAPI/dotnetcore_modules/ /opt/WorkFlowAPI/dotnetcore_modules_backup"
        - "mkdir /opt/WorkFlowAPI/dotnetcore_modules/" 
        - "cp -a ./Publish/. /opt/WorkFlowAPI/dotnetcore_modules/"
        - "systemctl start supervisord"

